version: '3'

services:
    db:
        image: postgres:9.6.5
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
    web:
        build: .
        command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports: 
            - "8000:8000"
        depends_on:
            - db
            - redis
    celery:
        build: .
        command: celery -A lyfe.tasks worker -l info
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
    celery:
        build: .
        command: celery -A lyfe.tasks beat -l info
        volumes:
            - .:/app
        depends_on:
            - db
            - redis

volumes:
    postgres_data:
